const data = [
  {
    name: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    price: 9.9,
    tags: ["Tradicional"],
  },
  {
    name: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    price: 9.9,
    tags: ["Tradicional"],
  },
  {
    name: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    price: 9.9,
    tags: ["Tradicional"],
  },
  {
    name: "Expresso Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: 9.9,
    tags: ["Tradicional", "Gelado"],
  },
  {
    name: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: 9.9,
    tags: ["Tradicional", "Com leite"],
  },
  // {
  //   id: 3,
  //   name: 'Phone Standard',
  //   price: 9.9,
  //   tags: ['Tradicional'],
  //   description: '',
  // },
  // {
  //   id: 1,
  //   name: 'Expre ',
  //   price: 9.9,
  //   tags: ['Tradicional'],
  //   description: 'A large phone with one of the best screens',
  // },
  // {
  //   id: 2,
  //   name: 'Phone Mini',
  //   price: 9.9,
  //   tags: ['Tradicional'],
  //   description: 'A great phone with one of the best cameras',
  // },
  // {
  //   id: 3,
  //   name: 'Phone Standard',
  //   price: 9.9,
  //   tags: ['Tradicional'],
  //   description: '',
  // },
  // {
  //   id: 1,
  //   name: 'Expre ',
  //   price: 9.9,
  //   tags: ['Tradicional'],
  //   description: 'A large phone with one of the best screens',
  // },
  // {
  //   id: 2,
  //   name: 'Phone Mini',
  //   price: 9.9,
  //   tags: ['Tradicional'],
  //   description: 'A great phone with one of the best cameras',
  // },
  // {
  //   id: 3,
  //   name: 'Phone Standard',
  //   price: 9.9,
  //   tags: ['Tradicional'],
  //   description: '',
  // },
  // {
  //   id: 1,
  //   name: 'Expre ',
  //   price: 9.9,
  //   tags: ['Tradicional'],
  //   description: 'A large phone with one of the best screens',
  // },
  // {
  //   id: 2,
  //   name: 'Phone Mini',
  //   price: 9.9,
  //   tags: ['Tradicional'],
  //   description: 'A great phone with one of the best cameras',
  // },
];

module.exports = data;
